server:
  port: 8083
  forward-headers-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      server:
        webmvc:
          trusted-proxies: ".*"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

resilience4j:
  timelimiter:
    instances:
      notificationServiceCircuitBreaker:
        timeoutDuration: 10s
        cancelRunningFuture: true