server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: file:./config-repo
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: health, info